[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "kev_os_x86_64.json"

[target.'cfg(target_os ="none")']
runner = "bootimage runner"
